name: torch-audiomentations-gpu
channels:
- defaults
- conda-forge
- pytorch-lts
dependencies:
- cudatoolkit=11.1
- ffmpeg
- matplotlib>=3,<4
- numpy>=1.15,<1.22
- pip>=20.1,<=21
- python=3.8.12
- pytorch-lts::pytorch=1.8.2
- pytorch-lts::torchaudio=0.8.2
- scipy=1.5.2
- seaborn>=0.9,<0.11
- pip:
  - audioread==2.1.8
  - black
  - coverage==5.3
  - julius>=0.2.3,<0.3
  - librosa==0.9.0
  - pandas==1.1.4
  - py-cpuinfo==7.0.0
  - pytest==5.3.4
  - pytest-cov==2.8.1
  - PyYAML==5.3.1
  - setuptools>=41.0.0
  - tqdm==4.49.0
  - twine
  - torch-pitch-shift>=1.2.0
